version: "3.9"
services:
  backend:
    build:
      context: ./backend-app     
      dockerfile: Dockerfile     
    ports:
      - "5000:5000"
    env_file:
      - ./backend-app/.env       
    volumes:
      - ./backend-app:/app       
    restart: unless-stopped
  frontend:
    build: ./frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend